In [14]:
import pandas as pd
import yfinance as yf
import financedatabase as fd

import importlib
import utils.price_increase as pi

importlib.reload(pi)

import requests
from bs4 import BeautifulSoup

import time
import random
import re

# from utils.price_increase import yearly_price_increase, multi_year_performance

In [15]:
# Get fund ticker data
fundsTicker = pd.read_csv("data/funds_ticker.csv")
euroFunds = fundsTicker[fundsTicker['currency'] == "EUR"]
euroFunds = euroFunds[["name", "symbol", "currency"]]
print(euroFunds.shape)
def findTicker(fundName, partialTicker):
    phrase = fundName[:20]

    matches = euroFunds[
        # (euroFunds["name"].str.contains(phrase, case=False, na=False)) 
                        #   & 
                          (euroFunds["symbol"].str.contains(partialTicker, case=False, na=False))]
    if matches.shape[0] > 1:
        m2 = matches[matches["symbol"].str.contains(rf"{partialTicker}\.", case=False, na=False)]
        if m2.shape[0] > 0:
            return m2
    return matches

tt = findTicker("BNP Paribas Easy MSCI Pacific ex Japan Min TE UCITS ETF", "PAC")
tt

(27875, 3)

                                                    name  symbol currency
23438  BNP Paribas Easy MSCI Pacific ex Japan ex CW U...  PAC.DE      EUR
23439                          BNPPE-MSCI PA.XJXCW.UECEO  PAC.DU      EUR
23440  BNP Paribas Easy MSCI Pacific ex Japan ex CW U...   PAC.F      EUR

In [22]:
etfData = pd.read_excel("data/etfs.xlsx")

# onlyEtf = etfData.where(etfData["assetClass"] == "equity").dropna()
onlyEtf = etfData[(etfData["asset_class"] == "equity") 
                #   & (etfData["currency"] == "EUR") 
                  & (etfData["dividends"] == "Accumulating") & (etfData["number_of_holdings"] > 50)]

onlyEtf = onlyEtf[["isin", "name", "ticker","size", "asset_class", "currency", "domicile_country", "hedged", "dividends", "ter", "number_of_holdings", "index"]]
print(onlyEtf.shape)
print(etfData.shape)

for index, row in onlyEtf.iterrows():
    try:
        possibleTickers = findTicker(row['name'], row['ticker'])
        if not possibleTickers.empty:
            # row["symbol"] = possibleTickers.iloc[0]['symbol']
            onlyEtf.loc[index, "symbol"] = possibleTickers.iloc[0]['symbol']
            print(f"Match found for {row['name']} with ticker {row['ticker']}: {row['symbol']}")
        # else:
        #     print(f"No match found for {row['name']} with ticker {row['ticker']}")
    except Exception as e:
        # print(f"Error processing {row['ticker']}: {e}")
        continue


onlyEtf.to_csv("etf-with-ticker.csv", index=False)
onlyEtf.head()

(958, 12)
(4062, 21)

,isin,name,ticker,size,asset_class,currency,domicile_country,hedged,dividends,ter,number_of_holdings,index,symbol
131,DE000A2QP4B6,iShares STOXX Europe 600 UCITS ETF (DE) EUR (Acc),EXIE,849.0,equity,EUR,Germany,False,Accumulating,0.20,600.0,STOXX® Europe 600,NaN
132,DE000A2QP4C4,iShares Dow Jones Global Titans 50 UCITS ETF (...,EXIF,4.0,equity,EUR,Germany,False,Accumulating,0.51,53.0,Dow Jones Global Titans 50,NaN
268,FR0007054358,Amundi EURO STOXX 50 II UCITS ETF Acc,LYSX,3923.0,equity,EUR,France,False,Accumulating,0.20,54.0,EURO STOXX® 50,LYSX.BE
275,FR0010261198,Amundi MSCI Europe UCITS ETF Acc,LYY5,611.0,equity,EUR,France,False,Accumulating,0.25,406.0,MSCI Europe,LYY5.BE
294,FR0010655704,Amundi CAC Transition Climat UCITS ETF,X13J,11.0,equity,EUR,France,False,Accumulating,0.25,69.0,CAC Transition Climat,X13J.BE

In [17]:
# Fetch historical data from yahoo finance for a given ticker
def fetchHistoricData(ticker):
    etf = yf.Ticker(ticker)

    current_year = pd.Timestamp.today().year
    start_year = current_year - 15   # inclusive = 10 years

    start = pd.Timestamp(f"{start_year}-01-01")
    end = pd.Timestamp(f"{current_year - 1}-12-31")

    hist = etf.history(start=start, end=end)
    if hist.empty:
        return None


    yearly = pi.yearly_price_increase(hist)

    tt =  yearly[['pct_increase']].T
    return tt
    perf = multi_year_performance(yearly, periods=(3,5,10))

    oneRow = perf.set_index('Years Ago')[['% Increase']].T.rename(columns={3: '3year', 5: '5year', 10: '10year'})
    # oneRow.index = [0] 
    # result = pd.DataFrame(oneRow.values, columns=oneRow.columns)
    return oneRow

In [53]:
data = fetchHistoricData("PAC.DE")
data

Not enough history to calculate 10-year performance.

/home/nerjok/Documents/fintech/utils/price_increase.py:66: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  nf = pd.concat([pd.DataFrame([new_row]), nf], ignore_index=True)

Year,5 year,3 year,1 year,2016-12-31 00:00:00+01:00,2017-12-31 00:00:00+01:00,2018-12-31 00:00:00+01:00,2019-12-31 00:00:00+01:00,2020-12-31 00:00:00+01:00,2021-12-31 00:00:00+01:00,2022-12-31 00:00:00+01:00,2023-12-31 00:00:00+01:00,2024-12-31 00:00:00+01:00,2025-12-31 00:00:00+01:00
pct_increase,38.879824,22.454854,6.727961,6.302722,7.004185,-95.721293,21.448477,-2.715567,12.83073,0.903076,1.489232,12.136832,5.392025

In [51]:
# from bs4 import soup


def justetf_perf(isin):
    url = f"https://www.justetf.com/en/etf-profile.html?isin={isin}"
    headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.justetf.com/"
    }
    html = requests.get(url, headers=headers).text
    soup = BeautifulSoup(html, "html.parser")
    
    perf = {}
    # rows = soup.select("table tbody tr")

    # Add volatility
    volatilityTable = soup.find("table", {"data-testid": "etf-basics_data_table"})
    rows2 = volatilityTable.find_all("tr")
    for r in rows2:
        cols2 = [c.text.strip() for c in r.find_all("td")]

        if len(cols2) != 2:
            continue
        if "Volatility" in cols2[0]:
            perf["Volatility"] = cols2[1]
            continue
        if len(cols2) == 2:
            perf[cols2[0]] = cols2[1]


    # Add performance
    table = soup.find("table", {"data-testid": "etf-returns-section_table"})
    if not table:
        return None

    data = {}

    rows = table.find_all("tr")
    # print(rows)
    for r in rows:
        cols = [c.text.strip() for c in r.find_all("td")]
        if len(cols) == 2:
            perf[cols[0]] = cols[1]
    # print(perf)
    perf_filtered = {k.rstrip('s'): v for k, v in perf.items() 
                     if k in ["1 year", "3 years", "5 years", "Volatility", "Fund size"]}
    df = pd.DataFrame(perf_filtered, index=[0])
    return df

print("Results for DE0005933931:")
print(justetf_perf("DE0005933931"))

Results for DE0005933931:
     Fund size Volatility   1 year   3 year   5 year
0  EUR 8,500 m     15.54%  +15.83%  +53.70%  +55.29%

In [55]:
#  Fetch historical data from etffDarabase list that calls justetf for each etf and combines the data into a single dataframe
# onlyEtf = onlyEtf.head(50)  # limit to 10 for testing
print(f"onlyEtf shape: {onlyEtf.shape}")
print(f"onlyEtf empty: {onlyEtf.empty}")
withHistory = pd.DataFrame()
print(onlyEtf.head(10))

def safe_sleep(base=2):
    jitter = random.uniform(0, 2)
    time.sleep(base + jitter)


i = 0
for index, row in onlyEtf.iterrows():
    # ticker = row["symbol"] if not pd.isna(row["symbol"]) else row["isin"]
    ticker = row["symbol"] if not pd.isna(row["symbol"]) else row["isin"]
    # i += 1
    # if i >100:
    #     break
    # print(f"Fetching data for {ticker}...")
    safe_sleep()  # be polite to the server
    try:


        perf = justetf_perf(row["isin"])

        if perf is None:
            perf = fetchHistoricData(ticker)
        if perf is not None:
            perf_dict = perf.iloc[0].to_dict()
            combined = {**row.to_dict(), **perf_dict}
            withHistory = pd.concat([withHistory, pd.DataFrame([combined])], ignore_index=True)
    except Exception as e:
        print(f"Error fetching data for {ticker}: {e}")
        continue


withHistory.to_csv("output/justetf_hist.csv", index=False)
withHistory

onlyEtf shape: (958, 13)
onlyEtf empty: False
             isin                                               name  ticker  \
131  DE000A2QP4B6  iShares STOXX Europe 600 UCITS ETF (DE) EUR (Acc)    EXIE
132  DE000A2QP4C4  iShares Dow Jones Global Titans 50 UCITS ETF (...    EXIF
268  FR0007054358              Amundi EURO STOXX 50 II UCITS ETF Acc    LYSX
275  FR0010261198                   Amundi MSCI Europe UCITS ETF Acc    LYY5
294  FR0010655704             Amundi CAC Transition Climat UCITS ETF    X13J
302  FR0010821819  Amundi ETF MSCI Europe Ex EMU ESG Leaders UCIT...    540H
317  FR0011720911                  Amundi MSCI China A UCITS ETF Acc    CNAA
318  FR0011758085      Amundi FTSE Italia PMI PIR 2020 UCITS ETF Acc  ITAMID
320  FR0012399731   Amundi EURO STOXX 50 II UCITS ETF CHF Hedged Acc    MSEC
321  FR0012399772   Amundi EURO STOXX 50 II UCITS ETF GBP Hedged Acc    NK4B

       size asset_class currency domicile_country  hedged     dividends   ter  \
131   849.0      equity      EUR          Germany   False  Accumulating  0.20
132     4.0      equity      EUR          Germany   False  Accumulating  0.51
268  3923.0      equity      EUR           France   False  Accumulating  0.20
275   611.0      equity      EUR           France   False  Accumulating  0.25
294    11.0      equity      EUR           France   False  Accumulating  0.25
302   230.0      equity      EUR           France   False  Accumulating  0.30
317   139.0      equity      USD           France   False  Accumulating  0.35
318   181.0      equity      EUR           France   False  Accumulating  0.40
320    87.0      equity      CHF           France    True  Accumulating  0.20
321    23.0      equity      GBP           France    True  Accumulating  0.20

     number_of_holdings                                              index  \
131               600.0                                  STOXX® Europe 600
132                53.0                         Dow Jones Global Titans 50
268                54.0                                     EURO STOXX® 50
275               406.0                                        MSCI Europe
294                69.0                              CAC Transition Climat
302               109.0  MSCI Europe ex EMU ESG Leaders Select 5% Issue...
317               384.0                                       MSCI China A
318                74.0                                FTSE Italia PIR PMI
320                54.0                        EURO STOXX® 50 (CHF Hedged)
321                54.0                        EURO STOXX® 50 (GBP Hedged)

        symbol
131        NaN
132        NaN
268    LYSX.BE
275    LYY5.BE
294    X13J.BE
302        NaN
317    CNAA.BE
318  ITAMID.MI
320        NaN
321        NaN
Error fetching data for IS3U.BE: 'NoneType' object has no attribute 'find_all'

,isin,name,ticker,size,asset_class,currency,domicile_country,hedged,dividends,ter,number_of_holdings,index,symbol,Fund size,Volatility,1 year,3 year,5 year
0,DE000A2QP4B6,iShares STOXX Europe 600 UCITS ETF (DE) EUR (Acc),EXIE,849.0,equity,EUR,Germany,False,Accumulating,0.20,600.0,STOXX® Europe 600,NaN,EUR 846 m,11.62%,+27.01%,+46.26%,-
1,DE000A2QP4C4,iShares Dow Jones Global Titans 50 UCITS ETF (...,EXIF,4.0,equity,EUR,Germany,False,Accumulating,0.51,53.0,Dow Jones Global Titans 50,NaN,EUR 7 m,-,-,-,-
2,FR0007054358,Amundi EURO STOXX 50 II UCITS ETF Acc,LYSX,3923.0,equity,EUR,France,False,Accumulating,0.20,54.0,EURO STOXX® 50,LYSX.BE,"EUR 4,186 m",14.99%,+26.19%,+51.15%,+72.76%
3,FR0010261198,Amundi MSCI Europe UCITS ETF Acc,LYY5,611.0,equity,EUR,France,False,Accumulating,0.25,406.0,MSCI Europe,LYY5.BE,EUR 628 m,11.57%,+26.39%,+44.42%,+62.66%
4,FR0010655704,Amundi CAC Transition Climat UCITS ETF,X13J,11.0,equity,EUR,France,False,Accumulating,0.25,69.0,CAC Transition Climat,X13J.BE,EUR 11 m,14.51%,+7.78%,+10.39%,+35.69%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952,LU2993390843,BNP Paribas Easy S&P 500 II UCITS ETF EUR Hedg...,EDEA,61.0,equity,EUR,Luxembourg,True,Accumulating,0.08,503.0,S&P 500® (EUR Hedged),NaN,EUR 64 m,-,-,-,-
953,LU3086388124,Amundi MSCI Europe Screened UCITS ETF (Acc),EUSC,389.0,equity,EUR,Luxembourg,False,Accumulating,0.12,375.0,MSCI Europe Screened Select ex Thermal Coal,NaN,EUR 551 m,-,-,-,-
954,LU3180074463,Amundi European Strategic Autonomy UCITS ETF Acc,INDEP,6.0,equity,EUR,Luxembourg,False,Accumulating,0.40,221.0,Euronext European Strategic Autonomy,NaN,EUR 14 m,-,-,-,-
955,XS2399364152,Leverage Shares 5x Long Nasdaq 100 ETP,QQQ5,28.0,equity,USD,Ireland,False,Accumulating,0.75,101.0,Nasdaq 100® Leverage (5x),NaN,EUR 30 m,83.16%,+254.35%,+340.54%,-
956,XS2399364319,Leverage Shares -5x Short Nasdaq 100 ETP,QQ3S,6.0,equity,USD,Ireland,False,Accumulating,0.75,101.0,Nasdaq 100® Short Leverage (-5x),NaN,EUR 6 m,93.65%,-90.24%,-98.10%,-

In [ ]:
# Fetch bonds data
def getContinent(country):
    df = pd.read_csv("data/countries_by_continents.csv")

    row = df[df["Country"].str.lower() == country.lower()]
    if not row.empty:
        # Return the continent value
        return row.iloc[0]["Continent"]
    else:
        return None

def fetch_bonds():
    url = f"https://www.investing.com/rates-bonds/world-government-bonds"
    headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.justetf.com/"
    }
    html = requests.get(url, headers=headers).text
    soup = BeautifulSoup(html, "html.parser")


    tablesContainer = soup.find("section", {"id": "leftColumn"})
    tables = tablesContainer.find_all("table" )
    if not tables:
        return None

    rows_data = []
    for table in tables:
        # if table.find_parent("div", class_="leftColumn") is None:
        #     continue
        if "displayNone" in table.get("class", []):
            continue

        rows = table.find_all("tr")
        for r in rows:
            cols = [c.text.strip() for c in r.find_all("td")]
                
            # keep only the first two columns (pad with None if fewer than 2)
            first_two = cols[1:3]
            # Convert yield to float safely
            # try:
            #     yield_value = float(first_two[1])
            # except ValueError:
            #     continue
            
            # # Skip yields below 3
            # if yield_value < 3:
            #     continue

            if len(first_two) < 2 or not first_two[1]:
                continue
            country = re.sub(r" \d+Y| \d+M", "",first_two[0])
            continent = getContinent(country)

            if continent == "Africa" and country != "Egipt":
                continue


            # rows_data.append([country, first_two[1]])
            rows_data.append([first_two[0], continent, first_two[1]])
        

    rows_data.sort(key=lambda x: float(x[2]) if x[1] else 0, reverse=True)

    df = pd.DataFrame(rows_data[1:])

    df.columns = ["Country", "Continent", "Yield"]
    # df = (
    # df.groupby("Country")["Yield"]
    #   .apply(lambda x: ",".join(sorted(map(str, x), reverse=True)))
    #   .reset_index()
    # )
    df["Yield"] = pd.to_numeric(df["Yield"], errors="coerce")
    df = df[df["Yield"] > 4]
    df.to_csv("output/bonds.csv", index=False)

    print(df)
    return rows_data

fetch_bonds()

       Country Continent   Yield
0    Turkey 9M    Europe  36.308
1    Turkey 6M    Europe  36.041
2    Turkey 3Y    Europe  35.960
3    Turkey 3M    Europe  35.417
4    Turkey 5Y    Europe  34.830
..         ...       ...     ...
633   U.K. 40Y      None   5.300
634   U.K. 50Y      None   4.878
645   U.S. 10Y      None   4.132
646   U.S. 20Y      None   4.727
647   U.S. 30Y      None   4.756

[269 rows x 3 columns]

[['Turkey 2Y', 'Europe', '38.770'],
 ['Turkey 9M', 'Europe', '36.308'],
 ['Turkey 6M', 'Europe', '36.041'],
 ['Turkey 3Y', 'Europe', '35.960'],
 ['Turkey 3M', 'Europe', '35.417'],
 ['Turkey 5Y', 'Europe', '34.830'],
 ['Turkey 10Y', 'Europe', '31.275'],
 ['Ukraine 1Y', 'Europe', '24.750'],
 ['Ukraine 2Y', 'Europe', '23.100'],
 ['Ukraine 3Y', 'Europe', '22.150'],
 ['Kazakhstan 6M', 'Asia', '16.650'],
 ['Kazakhstan 1Y', 'Asia', '16.164'],
 ['Kazakhstan 2Y', 'Asia', '16.036'],
 ['Kazakhstan 3Y', 'Asia', '15.700'],
 ['Kazakhstan 4Y', 'Asia', '15.434'],
 ['Kazakhstan 5Y', 'Asia', '15.300'],
 ['Kazakhstan 6Y', 'Asia', '15.171'],
 ['Kazakhstan 7Y', 'Asia', '15.089'],
 ['Kazakhstan 15Y', 'Asia', '15.028'],
 ['Kazakhstan 8Y', 'Asia', '15.017'],
 ['Kazakhstan 10Y', 'Asia', '15.011'],
 ['Kazakhstan 9Y', 'Asia', '15.004'],
 ['Russia 5Y', 'Asia', '14.755'],
 ['Russia 7Y', 'Asia', '14.745'],
 ['Russia 10Y', 'Asia', '14.595'],
 ['Russia 3Y', 'Asia', '14.579'],
 ['Brazil 3M', 'South America', '14.578'],
 ['Russia 2Y', 'Asia', '14.360'],
 ['Russia 15Y', 'Asia', '14.354'],
 ['Colombia 5Y', 'South America', '14.290'],
 ['Colombia 4Y', 'South America', '14.250'],
 ['Brazil 6M', 'South America', '14.230'],
 ['Russia 20Y', 'Asia', '14.202'],
 ['Brazil 8Y', 'South America', '13.998'],
 ['Brazil 10Y', 'South America', '13.995'],
 ['Russia 1Y', 'Asia', '13.995'],
 ['Colombia 2Y', 'South America', '13.900'],
 ['Brazil 9M', 'South America', '13.865'],
 ['Russia 6M', 'Asia', '13.688'],
 ['Colombia 15Y', 'South America', '13.600'],
 ['Brazil 5Y', 'South America', '13.587'],
 ['Russia 3M', 'Asia', '13.476'],
 ['Russia 2M', 'Asia', '13.389'],
 ['Colombia 10Y', 'South America', '13.366'],
 ['Russia 1M', 'Asia', '13.298'],
 ['Brazil 1Y', 'South America', '13.265'],
 ['Brazil 3Y', 'South America', '13.225'],
 ['Brazil 2Y', 'South America', '13.177'],
 ['Pakistan 20Y', 'Asia', '11.859'],
 ['Pakistan 14Y', 'Asia', '11.835'],
 ['Pakistan 10Y', 'Asia', '11.716'],
 ['Sri Lanka 15Y', 'Asia', '11.038'],
 ['Pakistan 5Y', 'Asia', '10.986'],
 ['Pakistan 3Y', 'Asia', '10.920'],
 ['Sri Lanka 10Y', 'Asia', '10.794'],
 ['Sri Lanka 9Y', 'Asia', '10.758'],
 ['Sri Lanka 8Y', 'Asia', '10.547'],
 ['Bangladesh 2Y', 'Asia', '10.490'],
 ['Bangladesh 20Y', 'Asia', '10.470'],
 ['Bangladesh 10Y', 'Asia', '10.400'],
 ['Bangladesh 15Y', 'Asia', '10.370'],
 ['Bangladesh 5Y', 'Asia', '10.350'],
 ['Sri Lanka 7Y', 'Asia', '10.231'],
 ['Bangladesh 6M', 'Asia', '10.010'],
 ['Bangladesh 1Y', 'Asia', '9.970'],
 ['Bangladesh 3M', 'Asia', '9.930'],
 ['Sri Lanka 5Y', 'Asia', '9.848'],
 ['Sri Lanka 6Y', 'Asia', '9.833'],
 ['Sri Lanka 4Y', 'Asia', '9.612'],
 ['Mexico 30Y', 'North America', '9.450'],
 ['Mexico 20Y', 'North America', '9.374'],
 ['Mexico 15Y', 'North America', '9.244'],
 ['Sri Lanka 3Y', 'Asia', '9.198'],
 ['Sri Lanka 2Y', 'Asia', '9.046'],
 ['Mexico 10Y', 'North America', '8.990'],
 ['Mexico 7Y', 'North America', '8.690'],
 ['Mexico 5Y', 'North America', '8.454'],
 ['Sri Lanka 1Y', 'Asia', '8.210'],
 ['Sri Lanka 6M', 'Asia', '8.050'],
 ['Sri Lanka 3M', 'Asia', '7.850'],
 ['Mexico 3Y', 'North America', '7.840'],
 ['India 40Y', 'Asia', '7.479'],
 ['India 30Y', 'Asia', '7.434'],
 ['India 24Y', 'Asia', '7.347'],
 ['Iceland 2Y', 'Europe', '7.241'],
 ['India 19Y', 'Asia', '7.227'],
 ['Mexico 1Y', 'North America', '7.220'],
 ['Hungary 20Y', 'Europe', '7.200'],
 ['Mexico 6M', 'North America', '7.130'],
 ['Mexico 9M', 'North America', '7.130'],
 ['Hungary 15Y', 'Europe', '7.120'],
 ['Mexico 3M', 'North America', '7.110'],
 ['India 15Y', 'Asia', '7.106'],
 ['Hungary 10Y', 'Europe', '7.020'],
 ['India 14Y', 'Asia', '7.001'],
 ['India 13Y', 'Asia', '6.986'],
 ['Mexico 1M', 'North America', '6.920'],
 ['Iceland 5Y', 'Europe', '6.862'],
 ['India 12Y', 'Asia', '6.839'],
 ['India 11Y', 'Asia', '6.824'],
 ['Indonesia 15Y', 'Asia', '6.795'],
 ['Indonesia 25Y', 'Asia', '6.791'],
 ['Indonesia 30Y', 'Asia', '6.786'],
 ['Romania 10Y', 'Europe', '6.750'],
 ['Romania 7Y', 'Europe', '6.720'],
 ['Indonesia 20Y', 'Asia', '6.716'],
 ['India 10Y', 'Asia', '6.688'],
 ['Hungary 5Y', 'Europe', '6.680'],
 ['India 8Y', 'Asia', '6.675'],
 ['Iceland 10Y', 'Europe', '6.636'],
 ['India 7Y', 'Asia', '6.634'],
 ['India 6Y', 'Asia', '6.607'],
 ['India 9Y', 'Asia', '6.599'],
 ['Indonesia 10Y', 'Asia', '6.588'],
 ['Peru 15Y', 'South America', '6.572'],
 ['Hungary 3Y', 'Europe', '6.560'],
 ['Romania 5Y', 'Europe', '6.550'],
 ['Philippines 20Y', 'Asia', '6.503'],
 ['Romania 3Y', 'Europe', '6.500'],
 ['Romania 4Y', 'Europe', '6.490'],
 ['Romania 2Y', 'Europe', '6.470'],
 ['India 5Y', 'Asia', '6.380'],
 ['Philippines 10Y', 'Asia', '6.311'],
 ['Bahrain 5Y', 'Asia', '6.302'],
 ['Romania 1Y', 'Europe', '6.300'],
 ['India 4Y', 'Asia', '6.290'],
 ['Romania 6M', 'Europe', '6.200'],
 ['Hungary 3M', 'Europe', '6.190'],
 ['Hungary 6M', 'Europe', '6.190'],
 ['Hungary 1Y', 'Europe', '6.140'],
 ['Philippines 7Y', 'Asia', '6.113'],
 ['Peru 30Y', 'South America', '6.104'],
 ['Peru 20Y', 'South America', '6.100'],
 ['Indonesia 5Y', 'Asia', '6.050'],
 ['India 3Y', 'Asia', '6.004'],
 ['Bahrain 2Y', 'Asia', '5.901'],
 ['Philippines 5Y', 'Asia', '5.888'],
 ['Jordan 18M', 'Asia', '5.735'],
 ['India 2Y', 'Asia', '5.700'],
 ['India 1Y', 'Asia', '5.640'],
 ['Philippines 4Y', 'Asia', '5.633'],
 ['Poland 10Y', 'Europe', '5.570'],
 ['Chile 30Y', 'South America', '5.550'],
 ['Philippines 3Y', 'Asia', '5.525'],
 ['India 6M', 'Asia', '5.510'],
 ['Chile 20Y', 'South America', '5.500'],
 ['Chile 10Y', 'South America', '5.325'],
 ['India 3M', 'Asia', '5.310'],
 ['Indonesia 1Y', 'Asia', '5.310'],
 ['Australia 30Y', 'Oceania', '5.297'],
 ['Qatar 30Y', 'Asia', '5.289'],
 ['Chile 8Y', 'South America', '5.280'],
 ['Indonesia 3Y', 'Asia', '5.266'],
 ['Australia 20Y', 'Oceania', '5.254'],
 ['Philippines 2Y', 'Asia', '5.227'],
 ['Serbia 10Y', 'Europe', '5.215'],
 ['Bahrain 1Y', 'Asia', '5.214'],
 ['New Zealand 20Y', 'Oceania', '5.136'],
 ['Bahrain 9M', 'Asia', '5.092'],
 ['Australia 15Y', 'Oceania', '5.068'],
 ['Bahrain 6M', 'Asia', '5.061'],
 ['Indonesia 6M', 'Asia', '5.059'],
 ['Bahrain 3M', 'Asia', '5.047'],
 ['Qatar 20Y', 'Asia', '5.038'],
 ['Chile 5Y', 'South America', '5.000'],
 ['Chile 4Y', 'South America', '4.990'],
 ['Indonesia 3M', 'Asia', '4.967'],
 ['Australia 12Y', 'Oceania', '4.915'],
 ['Poland 5Y', 'Europe', '4.905'],
 ['New Zealand 15Y', 'Oceania', '4.893'],
 ['Indonesia 1M', 'Asia', '4.886'],
 ['Australia 10Y', 'Oceania', '4.845'],
 ['Australia 9Y', 'Oceania', '4.784'],
 ['Chile 2Y', 'South America', '4.720'],
 ['Australia 8Y', 'Oceania', '4.710'],
 ['Poland 4Y', 'Europe', '4.705'],
 ['Serbia 7Y', 'Europe', '4.680'],
 ['Australia 7Y', 'Oceania', '4.657'],
 ['Philippines 6M', 'Asia', '4.621'],
 ['Chile 1Y', 'South America', '4.600'],
 ['Australia 6Y', 'Oceania', '4.553'],
 ['Poland 3Y', 'Europe', '4.543'],
 ['Vietnam 30Y', 'Asia', '4.540'],
 ['Serbia 3Y', 'Europe', '4.535'],
 ['New Zealand 10Y', 'Oceania', '4.515'],
 ['Vietnam 20Y', 'Asia', '4.499'],
 ['Australia 5Y', 'Oceania', '4.494'],
 ['Philippines 3M', 'Asia', '4.451'],
 ['Australia 4Y', 'Oceania', '4.447'],
 ['Australia 3Y', 'Oceania', '4.432'],
 ['Serbia 1Y', 'Europe', '4.420'],
 ['Italy 30Y', 'Europe', '4.419'],
 ['Peru 5Y', 'South America', '4.416'],
 ['France 30Y', 'Europe', '4.388'],
 ['Norway 20Y', 'Europe', '4.386'],
 ['Vietnam 15Y', 'Asia', '4.378'],
 ['Australia 2Y', 'Oceania', '4.369'],
 ['Norway 10Y', 'Europe', '4.361'],
 ['Italy 25Y', 'Europe', '4.347'],
 ['Israel 30Y', 'Asia', '4.317'],
 ['Malta 25Y', 'Europe', '4.315'],
 ['Vietnam 10Y', 'Asia', '4.306'],
 ['Australia 1Y', 'Oceania', '4.299'],
 ['Greece 30Y', 'Europe', '4.286'],
 ['Philippines 1M', 'Asia', '4.277'],
 ['Philippines 1Y', 'Asia', '4.277'],
 ['Slovakia 50Y', 'Europe', '4.277'],
 ['Israel 1M', 'Asia', '4.270'],
 ['Norway 5Y', 'Europe', '4.268'],
 ['France 25Y', 'Europe', '4.241'],
 ['New Zealand 7Y', 'Oceania', '4.236'],
 ['Belgium 30Y', 'Europe', '4.230'],
 ['Norway 3Y', 'Europe', '4.229'],
 ['Italy 20Y', 'Europe', '4.228'],
 ['Italy 50Y', 'Europe', '4.200'],
 ['Slovakia 30Y', 'Europe', '4.200'],
 ['Malta 20Y', 'Europe', '4.179'],
 ['Norway 1Y', 'Europe', '4.157'],
 ['Slovakia 18Y', 'Europe', '4.112'],
 ['Qatar 5Y', 'Asia', '4.104'],
 ['Norway 9M', 'Europe', '4.101'],
 ['France 50Y', 'Europe', '4.086'],
 ['France 20Y', 'Europe', '4.074'],
 ['Italy 15Y', 'Europe', '4.062'],
 ['Norway 6M', 'Europe', '4.049'],
 ['Spain 30Y', 'Europe', '4.047'],
 ['Malaysia 30Y', 'Asia', '4.027'],
 ['Belgium 50Y', 'Europe', '4.005'],
 ['Poland 2Y', 'Europe', '4.005'],
 ['Israel 20Y', 'Asia', '4.004'],
 ['Vietnam 7Y', 'Asia', '4.004'],
 ['Spain 25Y', 'Europe', '3.986'],
 ['New Zealand 5Y', 'Oceania', '3.982'],
 ['Peru 2Y', 'South America', '3.970'],
 ['Belgium 20Y', 'Europe', '3.965'],
 ['Vietnam 5Y', 'Asia', '3.962'],
 ['Malaysia 20Y', 'Asia', '3.961'],
 ['Portugal 30Y', 'Europe', '3.952'],
 ['Cyprus 30Y', 'Europe', '3.939'],
 ['Greece 20Y', 'Europe', '3.938'],
 ['France 15Y', 'Europe', '3.906'],
 ['Canada 30Y', 'North America', '3.866'],
 ['Slovenia 25Y', 'Europe', '3.853'],
 ['Israel 10Y', 'Asia', '3.815'],
 ['Finland 30Y', 'Europe', '3.811'],
 ['Bulgaria 7Y', 'Europe', '3.809'],
 ['Spain 20Y', 'Europe', '3.806'],
 ['Malaysia 15Y', 'Asia', '3.804'],
 ['Greece 15Y', 'Europe', '3.798'],
 ['Austria 40Y', 'Europe', '3.767'],
 ['Israel 3M', 'Asia', '3.767'],
 ['Belgium 15Y', 'Europe', '3.765'],
 ['Slovenia 20Y', 'Europe', '3.757'],
 ['Cyprus 20Y', 'Europe', '3.753'],
 ['Austria 25Y', 'Europe', '3.752'],
 ['Portugal 20Y', 'Europe', '3.751'],
 ['Austria 30Y', 'Europe', '3.750'],
 ['Spain 15Y', 'Europe', '3.741'],
 ['Canada 20Y', 'North America', '3.738'],
 ['Malta 10Y', 'Europe', '3.719'],
 ['Ireland 30Y', 'Europe', '3.699'],
 ['Slovakia 13Y', 'Europe', '3.694'],
 ['Austria 20Y', 'Europe', '3.685'],
 ['Austria 50Y', 'Europe', '3.651'],
 ['Japan 40Y', 'Asia', '3.642'],
 ['Italy 10Y', 'Europe', '3.637'],
 ['South Korea 20Y', 'Asia', '3.618'],
 ['Portugal 15Y', 'Europe', '3.617'],
 ['South Korea 10Y', 'Asia', '3.616'],
 ['Israel 6M', 'Asia', '3.610'],
 ['Greece 10Y', 'Europe', '3.602'],
 ['Poland 1M', 'Europe', '3.600'],
 ['Poland 2M', 'Europe', '3.600'],
 ['Italy 9Y', 'Europe', '3.592'],
 ['Ireland 25Y', 'Europe', '3.590'],
 ['Lithuania 10Y', 'Europe', '3.582'],
 ['Slovenia 15Y', 'Europe', '3.581'],
 ['Poland 1Y', 'Europe', '3.574'],
 ['Malaysia 10Y', 'Asia', '3.559'],
 ['Israel 1Y', 'Asia', '3.550'],
 ['Ireland 20Y', 'Europe', '3.540'],
 ['South Korea 30Y', 'Asia', '3.521'],
 ['Finland 15Y', 'Europe', '3.519'],
 ['France 10Y', 'Europe', '3.514'],
 ['Israel 5Y', 'Asia', '3.511'],
 ['Israel 9M', 'Asia', '3.508'],
 ['Israel 3Y', 'Asia', '3.507'],
 ['Austria 15Y', 'Europe', '3.504'],
 ['Israel 2Y', 'Asia', '3.495'],
 ['Netherlands 25Y', 'Europe', '3.479'],
 ['South Korea 5Y', 'Asia', '3.472'],
 ['Netherlands 30Y', 'Europe', '3.466'],
 ['Malaysia 7Y', 'Asia', '3.447'],
 ['Italy 8Y', 'Europe', '3.445'],
 ['South Korea 50Y', 'Asia', '3.436'],
 ['Germany 30Y', 'Europe', '3.433'],
 ['Ireland 15Y', 'Europe', '3.433'],
 ['Germany 25Y', 'Europe', '3.431'],
 ['Slovakia 10Y', 'Europe', '3.43'],
 ['South Korea 4Y', 'Asia', '3.426'],
 ['Hong Kong 20Y', 'Asia', '3.423'],
 ['Japan 30Y', 'Asia', '3.421'],
 ['Canada 10Y', 'North America', '3.414'],
 ['Vietnam 3Y', 'Asia', '3.398'],
 ['France 9Y', 'Europe', '3.391'],
 ['Cyprus 10Y', 'Europe', '3.354'],
 ['Germany 20Y', 'Europe', '3.350'],
 ['Slovakia 9Y', 'Europe', '3.350'],
 ['Spain 10Y', 'Europe', '3.349'],
 ['Netherlands 20Y', 'Europe', '3.348'],
 ['Malaysia 5Y', 'Asia', '3.324'],
 ['Vietnam 1Y', 'Asia', '3.318'],
 ['Belgium 10Y', 'Europe', '3.317'],
 ['Slovenia 10Y', 'Europe', '3.313'],
 ['Portugal 10Y', 'Europe', '3.306'],
 ['Italy 7Y', 'Europe', '3.296'],
 ['Spain 9Y', 'Europe', '3.293'],
 ['Greece 7Y', 'Europe', '3.281'],
 ['France 8Y', 'Europe', '3.268'],
 ['New Zealand 2Y', 'Oceania', '3.264'],
 ['Croatia 10Y', 'Europe', '3.258'],
 ['Netherlands 15Y', 'Europe', '3.255'],
 ['South Korea 3Y', 'Asia', '3.230'],
 ['Belgium 9Y', 'Europe', '3.225'],
 ['Slovakia 8Y', 'Europe', '3.211'],
 ['Germany 15Y', 'Europe', '3.210'],
 ['Vietnam 2Y', 'Asia', '3.207'],
 ['Japan 15Y', 'Asia', '3.203'],
 ['Portugal 9Y', 'Europe', '3.202'],
 ['Italy 6Y', 'Europe', '3.200'],
 ['Ireland 10Y', 'Europe', '3.193'],
 ['Greece 1M', 'Europe', '3.181'],
 ['Belgium 8Y', 'Europe', '3.176'],
 ['Austria 10Y', 'Europe', '3.166'],
 ['Finland 10Y', 'Europe', '3.153'],
 ['Denmark 30Y', 'Europe', '3.138'],
 ['Malta 3Y', 'Europe', '3.134'],
 ['France 7Y', 'Europe', '3.1337'],
 ['Canada 7Y', 'North America', '3.130'],
 ['Cyprus 7Y', 'Europe', '3.114'],
 ['Malaysia 3Y', 'Asia', '3.102'],
 ['Bulgaria 5Y', 'Europe', '3.100'],
 ['Spain 8Y', 'Europe', '3.095'],
 ['Slovenia 8Y', 'Europe', '3.093'],
 ['Portugal 8Y', 'Europe', '3.082'],
 ['Austria 9Y', 'Europe', '3.078'],
 ['Malta 5Y', 'Europe', '3.066'],
 ['Japan 20Y', 'Asia', '3.027'],
 ['Portugal 7Y', 'Europe', '3.020'],
 ['Belgium 7Y', 'Europe', '3.015'],
 ['Spain 7Y', 'Europe', '3.009'],
 ['Sweden 20Y', 'Europe', '3.005'],
 ['Italy 5Y', 'Europe', '2.997'],
 ['Hong Kong 15Y', 'Asia', '2.994'],
 ['Austria 8Y', 'Europe', '2.992'],
 ['South Korea 2Y', 'Asia', '2.992'],
 ['Slovakia 6Y', 'Europe', '2.99'],
 ['France 6Y', 'Europe', '2.988'],
 ['Slovenia 7Y', 'Europe', '2.987'],
 ['Netherlands 10Y', 'Europe', '2.960'],
 ['Finland 8Y', 'Europe', '2.957'],
 ['Canada 5Y', 'North America', '2.953'],
 ['Greece 5Y', 'Europe', '2.951'],
 ['Denmark 20Y', 'Europe', '2.93'],
 ['Croatia 5Y', 'Europe', '2.914'],
 ['Ireland 7Y', 'Europe', '2.912'],
 ['Italy 4Y', 'Europe', '2.911'],
 ['Spain 6Y', 'Europe', '2.909'],
 ['Austria 7Y', 'Europe', '2.900'],
 ['Bulgaria 4Y', 'Europe', '2.900'],
 ['France 5Y', 'Europe', '2.889'],
 ['Lithuania 5Y', 'Europe', '2.884'],
 ['Netherlands 9Y', 'Europe', '2.884'],
 ['Malaysia 1Y', 'Asia', '2.880'],
 ['Belgium 6Y', 'Europe', '2.872'],
 ['Portugal 6Y', 'Europe', '2.872'],
 ['Germany 10Y', 'Europe', '2.8643'],
 ['Malaysia 7M', 'Asia', '2.860'],
 ['Malaysia 3M', 'Asia', '2.840'],
 ['South Korea 1Y', 'Asia', '2.831'],
 ['Hong Kong 10Y', 'Asia', '2.826'],
 ['Spain 5Y', 'Europe', '2.822'],
 ['Austria 6Y', 'Europe', '2.818'],
 ['Netherlands 8Y', 'Europe', '2.818'],
 ['Denmark 10Y', 'Europe', '2.784'],
 ['New Zealand 1Y', 'Oceania', '2.782'],
 ['Finland 6Y', 'Europe', '2.772'],
 ['Canada 4Y', 'North America', '2.768'],
 ['Netherlands 7Y', 'Europe', '2.767'],
 ['Germany 9Y', 'Europe', '2.765'],
 ['Portugal 5Y', 'Europe', '2.760'],
 ['Bulgaria 3Y', 'Europe', '2.754'],
 ['Belgium 5Y', 'Europe', '2.741'],
 ['Italy 3Y', 'Europe', '2.724'],
 ['Slovakia 5Y', 'Europe', '2.714'],
 ['Lithuania 3Y', 'Europe', '2.707'],
 ['Austria 5Y', 'Europe', '2.706'],
 ['Ireland 6Y', 'Europe', '2.706'],
 ['France 4Y', 'Europe', '2.703'],
 ['Slovenia 5Y', 'Europe', '2.697'],
 ['Germany 8Y', 'Europe', '2.696'],
 ['Sweden 10Y', 'Europe', '2.696'],
 ['Thailand 20Y', 'Asia', '2.696'],
 ['Cyprus 4Y', 'Europe', '2.691'],
 ['Ireland 4Y', 'Europe', '2.689'],
 ['France 3Y', 'Europe', '2.683'],
 ['Finland 5Y', 'Europe', '2.674'],
 ['Spain 4Y', 'Europe', '2.664'],
 ['Croatia 4Y', 'Europe', '2.655'],
 ['Netherlands 6Y', 'Europe', '2.655'],
 ['Germany 7Y', 'Europe', '2.648'],
 ['Canada 3Y', 'North America', '2.645'],
 ['New Zealand 6M', 'Oceania', '2.640'],
 ['Canada 2Y', 'North America', '2.636'],
 ['Denmark 8Y', 'Europe', '2.617'],
 ['Belgium 4Y', 'Europe', '2.611'],
 ['Greece 2Y', 'Europe', '2.602'],
 ['Austria 4Y', 'Europe', '2.601'],
 ['New Zealand 5M', 'Oceania', '2.600'],
 ['Ireland 5Y', 'Europe', '2.595'],
 ['Slovenia 4Y', 'Europe', '2.593'],
 ['Spain 3Y', 'Europe', '2.579'],
 ['Slovakia 2Y', 'Europe', '2.565'],
 ['Netherlands 5Y', 'Europe', '2.562'],
 ['Belgium 3Y', 'Europe', '2.557'],
 ['Finland 4Y', 'Europe', '2.552'],
 ['Croatia 3Y', 'Europe', '2.551'],
 ['New Zealand 4M', 'Oceania', '2.550'],
 ['Germany 5Y', 'Europe', '2.528'],
 ['Germany 6Y', 'Europe', '2.525'],
 ['New Zealand 3M', 'Oceania', '2.520'],
 ['Netherlands 4Y', 'Europe', '2.514'],
 ['Croatia 2Y', 'Europe', '2.506'],
 ['Bulgaria 2Y', 'Europe', '2.500'],
 ['Slovenia 3Y', 'Europe', '2.499'],
 ['Italy 2Y', 'Europe', '2.493'],
 ['New Zealand 2M', 'Oceania', '2.490'],
 ['Ireland 3Y', 'Europe', '2.487'],
 ['Spain 2Y', 'Europe', '2.486'],
 ['Portugal 4Y', 'Europe', '2.481'],
 ['Austria 3Y', 'Europe', '2.479'],
 ['New Zealand 1M', 'Oceania', '2.470'],
 ['Thailand 16Y', 'Asia', '2.467'],
 ['Sweden 7Y', 'Europe', '2.464'],
 ['Hong Kong 7Y', 'Asia', '2.460'],
 ['Denmark 5Y', 'Europe', '2.458'],
 ['Portugal 3Y', 'Europe', '2.445'],
 ['Bulgaria 1Y', 'Europe', '2.438'],
 ['Finland 3Y', 'Europe', '2.434'],
 ['France 2Y', 'Europe', '2.425'],
 ['Germany 4Y', 'Europe', '2.418'],
 ['Canada 1Y', 'North America', '2.415'],
 ['Netherlands 3Y', 'Europe', '2.415'],
 ['Austria 2Y', 'Europe', '2.401'],
 ['Slovenia 1Y', 'Europe', '2.400'],
 ['Malta 1Y', 'Europe', '2.390'],
 ['Sweden 5Y', 'Europe', '2.383'],
 ['Portugal 2Y', 'Europe', '2.381'],
 ['Finland 2Y', 'Europe', '2.369'],
 ['Ireland 2Y', 'Europe', '2.364'],
 ['Greece 3M', 'Europe', '2.352'],
 ['Belgium 2Y', 'Europe', '2.349'],
 ['Greece 6M', 'Europe', '2.332'],
 ['Netherlands 2Y', 'Europe', '2.321'],
 ['China 20Y', 'Asia', '2.314'],
 ['Ireland 1Y', 'Europe', '2.313'],
 ['Germany 2Y', 'Europe', '2.311'],
 ['Thailand 15Y', 'Asia', '2.310'],
 ['Austria 1Y', 'Europe', '2.308'],
 ['Denmark 3Y', 'Europe', '2.308'],
 ['Italy 1Y', 'Europe', '2.308'],
 ['Germany 3Y', 'Europe', '2.302'],
 ['China 30Y', 'Asia', '2.291'],
 ['Canada 6M', 'North America', '2.290'],
 ['Singapore 50Y', 'Asia', '2.285'],
 ['France 9M', 'Europe', '2.283'],
 ['France 1Y', 'Europe', '2.276'],
 ['Italy 9M', 'Europe', '2.249'],
 ['Portugal 1Y', 'Europe', '2.240'],
 ['Hong Kong 5Y', 'Asia', '2.231'],
 ['Malta 6M', 'Europe', '2.224'],
 ['Spain 1Y', 'Europe', '2.222'],
 ['Canada 2M', 'North America', '2.220'],
 ['Canada 3M', 'North America', '2.210'],
 ['Belgium 9M', 'Europe', '2.207'],
 ['Canada 1M', 'North America', '2.200'],
 ['Spain 9M', 'Europe', '2.195'],
 ['Italy 6M', 'Europe', '2.193'],
 ['Thailand 14Y', 'Asia', '2.183'],
 ['Japan 10Y', 'Asia', '2.179'],
 ['Hong Kong 3Y', 'Asia', '2.171'],
 ['France 6M', 'Europe', '2.164'],
 ['Greece 1Y', 'Europe', '2.164'],
 ['Hong Kong 2Y', 'Asia', '2.159'],
 ['Japan 9Y', 'Asia', '2.155'],
 ['Singapore 30Y', 'Asia', '2.155'],
 ['Belgium 6M', 'Europe', '2.147'],
 ['Thailand 12Y', 'Asia', '2.145'],
 ['Germany 1Y', 'Europe', '2.144'],
 ['Malta 3M', 'Europe', '2.141'],
 ['Hong Kong 6M', 'Asia', '2.130'],
 ['Denmark 2Y', 'Europe', '2.123'],
 ['Spain 6M', 'Europe', '2.123'],
 ['Germany 9M', 'Europe', '2.108'],
 ['Singapore 20Y', 'Asia', '2.103'],
 ['France 3M', 'Europe', '2.101'],
 ['Malta 1M', 'Europe', '2.094'],
 ['Belgium 3M', 'Europe', '2.084'],
 ['Italy 3M', 'Europe', '2.084'],
 ['Hong Kong 9M', 'Asia', '2.080'],
 ['Hong Kong 1Y', 'Asia', '2.080'],
 ['Singapore 15Y', 'Asia', '2.080'],
 ['Sweden 2Y', 'Europe', '2.080'],
 ['Croatia 1Y', 'Europe', '2.071'],
 ['France 1M', 'Europe', '2.070'],
 ['Netherlands 6M', 'Europe', '2.064'],
 ['Japan 8Y', 'Asia', '2.063'],
 ['Hong Kong 3M', 'Asia', '2.061'],
 ['Austria 3M', 'Europe', '2.051'],
 ['Austria 6M', 'Europe', '2.051'],
 ['China 15Y', 'Asia', '2.043'],
 ['Germany 6M', 'Europe', '2.041'],
 ['Netherlands 3M', 'Europe', '2.022'],
 ['Spain 1M', 'Europe', '2.005'],
 ['Portugal 3M', 'Europe', '2.003'],
 ['Spain 3M', 'Europe', '2.000'],
 ['Netherlands 1M', 'Europe', '1.999'],
 ['Singapore 10Y', 'Asia', '1.994'],
 ['Germany 3M', 'Europe', '1.988'],
 ['Italy 1M', 'Europe', '1.983'],
 ['Sweden 6M', 'Europe', '1.976'],
 ['Hong Kong 1M', 'Asia', '1.945'],
 ['Sweden 2M', 'Europe', '1.944'],
 ['Sweden 3M', 'Europe', '1.944'],
 ['Denmark 6M', 'Europe', '1.934'],
 ['Japan 7Y', 'Asia', '1.924'],
 ['Thailand 10Y', 'Asia', '1.892'],
 ['Denmark 3M', 'Europe', '1.864'],
 ['Sweden 1M', 'Europe', '1.846'],
 ['Japan 6Y', 'Asia', '1.838'],
 ['China 10Y', 'Asia', '1.797'],
 ['Chile 4Y', 'South America', '1.780'],
 ['Portugal 6M', 'Europe', '1.757'],
 ['Taiwan 30Y', 'Asia', '1.660'],

In [29]:
df = pd.read_csv("data/countries_by_continents.csv")

# df = pd.read_excel(xlsx, "Sheet1")

df

country = df[df["Country"] == "Germany"]
country

    Continent  Country
117    Europe  Germany

In [63]:
# Yearl ygrowth to decimal

df = pd.read_csv("output/justetf_hist.csv")

def parse_percent(x):
    if pd.isna(x) or x == '-':
        return None
    return float(x.replace('%','').replace('+','')) / 100

df['return_1y'] = df['1 year'].apply(parse_percent)
df['return_3y'] = df['3 year'].apply(parse_percent)
df['return_5y'] = df['5 year'].apply(parse_percent)
df['volatility'] = df['Volatility'].apply(parse_percent)

df = df.dropna(subset=['volatility'])

#  different set of time period
df['expected_return'] = df['return_3y']

# Sharpe ratio with 0% risk free rate
df['annual_return'] = (1 + df['return_3y']) ** (1/3) - 1
df['score'] = df['annual_return'] / df['volatility']

df.head()

,isin,name,ticker,size,asset_class,currency,domicile_country,hedged,dividends,ter,...,1 year,3 year,5 year,return_1y,return_3y,return_5y,volatility,expected_return,annual_return,score
0,DE000A2QP4B6,iShares STOXX Europe 600 UCITS ETF (DE) EUR (Acc),EXIE,849.0,equity,EUR,Germany,False,Accumulating,0.20,...,+27.01%,+46.26%,-,0.2701,0.4626,NaN,0.1162,0.4626,0.135120,1.162825
2,FR0007054358,Amundi EURO STOXX 50 II UCITS ETF Acc,LYSX,3923.0,equity,EUR,France,False,Accumulating,0.20,...,+26.19%,+51.15%,+72.76%,0.2619,0.5115,0.7276,0.1499,0.5115,0.147632,0.984871
3,FR0010261198,Amundi MSCI Europe UCITS ETF Acc,LYY5,611.0,equity,EUR,France,False,Accumulating,0.25,...,+26.39%,+44.42%,+62.66%,0.2639,0.4442,0.6266,0.1157,0.4442,0.130340,1.126535
4,FR0010655704,Amundi CAC Transition Climat UCITS ETF,X13J,11.0,equity,EUR,France,False,Accumulating,0.25,...,+7.78%,+10.39%,+35.69%,0.0778,0.1039,0.3569,0.1451,0.1039,0.033499,0.230866
5,FR0010821819,Amundi ETF MSCI Europe Ex EMU ESG Leaders UCIT...,540H,230.0,equity,EUR,France,False,Accumulating,0.30,...,+15.71%,+26.67%,+47.27%,0.1571,0.2667,0.4727,0.1165,0.2667,0.081993,0.703806

In [72]:
# Return etfs with best risk adjusted return (score) for each region and risk level
def parse_percent(x):
    if pd.isna(x) or x == '-':
        return None
    return float(x.replace('%','').replace('+','')) / 100


def build_portfolio(user, etf_df, bonds_df):
    
    # --- 1. PREPARE ETF DATA ---
    etf_df = etf_df.copy()
    
    etf_df['return_3y'] = etf_df['3 year'].apply(parse_percent)
    etf_df['volatility'] = etf_df['Volatility'].apply(parse_percent)

    # Remove rows with missing return or volatility
    etf_df = etf_df.dropna(subset=['return_3y', 'volatility'])

    # Annualize return
    etf_df['annual_return'] = (1 + etf_df['return_3y']) ** (1/3) - 1

    # Score (risk-adjusted) Sharp ratio with 0% risk free rate
    etf_df['score'] = etf_df['annual_return'] / etf_df['volatility']


    # --- 2. FILTER BY USER INPUT ---

    # Risk filter
    def risk_filter(df):
        if user["riskLevel"] == "low":
            return df[df['volatility'] < 0.10]
        elif user["riskLevel"] == "medium":
            return df[(df['volatility'] >= 0.10) & (df['volatility'] < 0.20)]
        else:
            return df[df['volatility'] >= 0.20]

    etf_df = risk_filter(etf_df)

    # Region filter, TODO add where securities are listed, not only domicile
    if not user["selectedRegions"].get("global"):
        if user["selectedRegions"].get("us"):
            etf_df = etf_df[etf_df['domicile_country'] == "USA"]


    # --- 3. PICK BEST ETFs ---
    etf_df = etf_df.sort_values(by='score', ascending=False).head(15)


    # --- 4. CALCULATE TOTAL MONEY ---
    years = int(user["years"].replace("y", ""))
    total_amount = user["perYearInvestment"] * years


    # --- 5. SPLIT ETF / BONDS ---
    risk_split = {
        "low":   {"etf": 0.3, "bonds": 0.7},
        "medium":{"etf": 0.6, "bonds": 0.4},
        "high":  {"etf": 0.9, "bonds": 0.1}
    }

    split = risk_split[user["riskLevel"]]

    etf_budget = total_amount * split["etf"]
    bonds_budget = total_amount * split["bonds"]


    # --- 6. ALLOCATE ETF MONEY ---
    etf_df['weight'] = etf_df['score'] / etf_df['score'].sum()
    etf_df['allocation'] = etf_df['weight'] * etf_budget


    # --- 7. ALLOCATE BONDS ---
    bonds_df = bonds_df.copy()
    bonds_df['allocation'] = bonds_budget / len(bonds_df)


    # --- 8. RETURN RESULT ---
    portfolio = []

    for _, row in etf_df.iterrows():
        portfolio.append({
            "type": "ETF",
            "name": row["name"],
            "ticker": row["ticker"],
            "allocation": round(row["allocation"], 2)
        })

    for _, row in bonds_df.iterrows():
        portfolio.append({
            "type": "Bond",
            "name": row["name"],
            "allocation": round(row["allocation"], 2)
        })

    return portfolio

In [76]:
# Call roboadvisor function
user = {
    "assetClasses": "ETFs",
    "perYearInvestment": 500,
    "riskLevel": "low",
    "selectedRegions": {"global": True, "us": True},
    "years": "3y"
}

bondDf =  pd.DataFrame({
    "name": ["US 10Y", "Germany 10Y"],
    "allocation": [5000, 5000]
})
portfolio = build_portfolio(user, df, bondDf)

for p in portfolio:
    print(p)

{'type': 'ETF', 'name': 'First Trust Global Equity Income UCITS ETF Acc', 'ticker': 'FTG4', 'allocation': 41.39}
{'type': 'ETF', 'name': 'WisdomTree Europe Equity Income UCITS ETF Acc', 'ticker': 'EEIP', 'allocation': 33.98}
{'type': 'ETF', 'name': 'Vanguard LifeStrategy 40% Equity UCITS ETF Accumulating', 'ticker': 'V40A', 'allocation': 31.3}
{'type': 'ETF', 'name': 'Vanguard LifeStrategy 60% Equity UCITS ETF Accumulating', 'ticker': 'V60A', 'allocation': 31.1}
{'type': 'ETF', 'name': 'Vanguard LifeStrategy 80% Equity UCITS ETF (EUR) Accumulating', 'ticker': 'V80A', 'allocation': 30.63}
{'type': 'ETF', 'name': 'Xtrackers Portfolio UCITS ETF 1C', 'ticker': 'XQUI', 'allocation': 30.28}
{'type': 'ETF', 'name': 'WisdomTree Emerging Markets Equity Income UCITS ETF Acc', 'ticker': 'WTD8', 'allocation': 29.14}
{'type': 'ETF', 'name': 'iShares Moderate Portfolio UCITS ETF EUR (Acc)', 'ticker': 'MODR', 'allocation': 29.08}
{'type': 'ETF', 'name': 'Invesco Global Active Defensive ESG Equity UCITS ETF EUR PfHdg Acc', 'ticker': 'LVLE', 'allocation': 28.59}
{'type': 'ETF', 'name': 'Goshawk Global Balanced Fund UCITS ETF Accumulating', 'ticker': 'ROE', 'allocation': 27.89}
{'type': 'ETF', 'name': 'Vanguard LifeStrategy 20% Equity UCITS ETF Accumulating', 'ticker': 'V20A', 'allocation': 27.69}
{'type': 'ETF', 'name': 'JPMorgan Global Equity Multi-Factor UCITS ETF Accumulating', 'ticker': 'JPGL', 'allocation': 27.6}
{'type': 'ETF', 'name': 'iShares MSCI World Quality Dividend Advanced UCITS ETF USD (Acc)', 'ticker': 'AYEG', 'allocation': 27.5}
{'type': 'ETF', 'name': 'UBS Global Gender Equality UCITS ETF USD acc', 'ticker': 'GENE', 'allocation': 27.0}
{'type': 'ETF', 'name': 'SPDR EURO STOXX Low Volatility UCITS ETF EUR', 'ticker': 'ZPRL', 'allocation': 26.83}
{'type': 'Bond', 'name': 'US 10Y', 'allocation': 525.0}
{'type': 'Bond', 'name': 'Germany 10Y', 'allocation': 525.0}